"use server";

import JSZip from "jszip";
import { createServiceClient } from "@/lib/supabase/server";
import { slugify } from "@/lib/onboarding/slug";
import { validateOnboardingSession, InvalidOnboardingSessionError } from "@/lib/onboarding/session";
import type { PricingTier } from "@pdc/shared-types";

export interface GeneratePackageResult {
  success: boolean;
  error?: string;
  /** Base64-encoded ZIP bytes. Server actions cannot stream a
   * Content-Disposition download directly (that's a Route Handler
   * concept) — the caller (SelfHostedPath.tsx) decodes this into a Blob
   * client-side and triggers the browser download from there. Documented
   * as a deliberate divergence from the prompt's literal HTTP-header
   * framing in the Session 6 report. */
  filename?: string;
  base64Zip?: string;
}

function routePathFor(tier: PricingTier): string {
  return tier.path || `/${slugify(tier.name)}`;
}

/**
 * Builds the self-hosted provider's index.ts. This ships OUTSIDE the PDC
 * monorepo (a provider's own Railway/Render/VPS repo, installed from the
 * public npm registry) — it cannot depend on @pdc/x402-adapter, which is a
 * private, unpublished workspace package. CLAUDE.md's "always via
 * pdc-x402-adapter" rule (Section 17/18) governs SBP's own services in this
 * monorepo; it has no npm-installable target for code that lives in a
 * third party's separate repository. This template inlines the same
 * gate/canonical-hash logic pdc-x402-adapter and apps/pilot-endpoint use,
 * built directly on @x402/hono + @x402/avm + @x402/core (pinned to the same
 * 2.19.x line) so a self-hosted provider gets equivalent, tested behaviour.
 * Flagged explicitly in the Session 6 report as a deliberate, unavoidable
 * exception scoped to generated code that never runs inside this monorepo.
 */
function buildIndexTs(params: {
  title: string;
  description: string;
  institutionName: string;
  country: string;
  category: string;
  subCategory: string | null;
  pricingTiers: PricingTier[];
}): string {
  const routesLiteral = params.pricingTiers
    .map(
      (tier) => `  {
    method: "GET",
    path: ${JSON.stringify(routePathFor(tier))},
    priceUsdc: ${tier.price_usdc},
    description: ${JSON.stringify(tier.description || tier.name)},
    tier: ${tier.tier},
  },`,
    )
    .join("\n");

  return `/**
 * ${params.institutionName} — Pacific Data Commons provider endpoint
 * Generated by Pacific Data Commons onboarding (Step 6 — self-hosted path).
 *
 * REQUIRED before deploying: replace DATASET_RECORDS below with your real
 * data. SBP never receives or stores your dataset (CLAUDE.md P1 — data
 * sovereignty); this file is generated from your approved listing metadata
 * only, not your data.
 */
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { createHash } from "node:crypto";
import {
  x402ResourceServer,
  HTTPFacilitatorClient,
  type RouteConfig,
  type RoutesConfig,
} from "@x402/core/server";
import type { Network } from "@x402/core/types";
import { ALGORAND_MAINNET_CAIP2, ALGORAND_TESTNET_CAIP2 } from "@x402/avm";
import { ExactAvmScheme } from "@x402/avm/exact/server";
import { paymentMiddleware } from "@x402/hono";

// ── 1. YOUR DATA — replace this with your real dataset ─────────────────────
const DATASET_RECORDS: Record<string, unknown>[] = [
  // { ...your records here... }
];

// ── 2. Configuration (from environment — CLAUDE.md P4: no secrets in code) ──
const PORT = Number(process.env.PORT ?? 8080);
const PUBLIC_URL = process.env.PUBLIC_URL ?? \`http://localhost:\${PORT}\`;
const ALGORAND_NETWORK = (process.env.ALGORAND_NETWORK ?? "mainnet") as "mainnet" | "testnet";
const PROVIDER_WALLET = process.env.PROVIDER_WALLET;
const FACILITATOR_URL = process.env.FACILITATOR_URL ?? "https://facilitator.goplausible.xyz";

if (!PROVIDER_WALLET) {
  throw new Error("PROVIDER_WALLET is required — set it in your environment before starting this server.");
}

// ── 3. Pre-filled listing metadata (from your approved PDC review) ─────────
const LISTING = {
  title: ${JSON.stringify(params.title)},
  description: ${JSON.stringify(params.description)},
  institution: ${JSON.stringify(params.institutionName)},
  country: ${JSON.stringify(params.country)},
  category: ${JSON.stringify(params.category)},
  sub_category: ${JSON.stringify(params.subCategory ?? "")},
  competition_tag: "x402-global-challenge",
};

// ── 4. Canonical dataset hash (CLAUDE.md Section 10 — mandatory before any
// pilot provider goes live). Computed once at startup, reused per request.
function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(record).sort((a, b) => a.localeCompare(b))) sorted[key] = canonicalize(record[key]);
    return sorted;
  }
  return value;
}
function computeCanonicalHash(records: unknown[]): string {
  return createHash("sha256").update(JSON.stringify(canonicalize(records)), "utf8").digest("hex");
}
const datasetHash = computeCanonicalHash(DATASET_RECORDS);
const hashComputedAt = new Date().toISOString();

// ── 5. Pricing tiers from your approved review (Step 4) ────────────────────
const PRICING_TIERS = [
${routesLiteral}
] as const;

// ── 6. x402 payment gate — pinned to @x402/* 2.19.x, same as the PDC
// monorepo's pdc-x402-adapter (see comment above about why this file can't
// import that package directly).
const CAIP2_NETWORK: Network = (ALGORAND_NETWORK === "mainnet" ? ALGORAND_MAINNET_CAIP2 : ALGORAND_TESTNET_CAIP2) as Network;
const facilitator = new HTTPFacilitatorClient({ url: FACILITATOR_URL });
const resourceServer = new x402ResourceServer(facilitator).register(CAIP2_NETWORK, new ExactAvmScheme());

const routesConfig: Record<string, RouteConfig> = {};
for (const route of PRICING_TIERS) {
  routesConfig[\`GET \${route.path}\`] = {
    accepts: {
      scheme: "exact",
      payTo: PROVIDER_WALLET,
      price: route.priceUsdc,
      network: CAIP2_NETWORK,
      extra: { tag: "x402-global-challenge", tier: route.tier },
    },
    resource: \`\${LISTING.institution}:\${route.path}\`,
    description: route.description,
  };
}

const app = new Hono();

app.get("/health", (c) =>
  c.json({ status: "healthy", dataset: { title: LISTING.title, records: DATASET_RECORDS.length, canonical_hash: datasetHash }, timestamp: new Date().toISOString() }),
);

app.get("/integrity", (c) =>
  c.json({
    hash: datasetHash,
    algorithm: "sha256",
    canonical_rule: "JSON keys sorted alphabetically, no whitespace, UTF-8 encoding",
    records_count: DATASET_RECORDS.length,
    computed_at: hashComputedAt,
  }),
);

app.get("/schema", (c) => c.json({ schema_version: "pdp-1.0", ...LISTING, pricing: PRICING_TIERS }));

app.use("*", paymentMiddleware(routesConfig as RoutesConfig, resourceServer));

for (const route of PRICING_TIERS) {
  app.get(route.path, (c) =>
    c.json({
      schema_version: "pdp-1.0",
      category: LISTING.category,
      sub_category: LISTING.sub_category,
      data_warning: "Replace DATASET_RECORDS with your real dataset before going live.",
      provider: {
        institution: LISTING.institution,
        country: LISTING.country,
        trust_tier: "bronze",
        competition_tag: LISTING.competition_tag,
        provenance_hash: datasetHash,
        integrity_url: \`\${PUBLIC_URL}/integrity\`,
      },
      query: { parameters_received: {}, parameters_applied: {}, records_returned: DATASET_RECORDS.length, records_total: DATASET_RECORDS.length },
      data: DATASET_RECORDS,
      methodology_summary: LISTING.description,
      citation: \`\${LISTING.institution}, accessed via Pacific Data Commons\`,
      accessed_at: new Date().toISOString(),
      paid_tier: String(route.tier),
      amount_paid_usdc: route.priceUsdc,
    }),
  );
}

app.notFound((c) => c.json({ error: "Route not found", code: "NOT_FOUND" }, 404));

serve({ fetch: app.fetch, port: PORT }, (info) => {
  console.log(\`[pdc-endpoint] listening on port \${info.port} — network: algorand-\${ALGORAND_NETWORK}\`);
});
`;
}

function buildPackageJson(providerSlug: string): string {
  return JSON.stringify(
    {
      name: `pdc-endpoint-${providerSlug}`,
      version: "1.0.0",
      private: true,
      type: "module",
      description: "Pacific Data Commons provider endpoint — self-hosted.",
      scripts: {
        dev: "tsx watch index.ts",
        build: "tsc index.ts --module esnext --target es2022 --moduleResolution bundler --outDir dist",
        start: "node dist/index.js",
      },
      dependencies: {
        "@hono/node-server": "^1.14.0",
        "@x402/avm": "^2.19.0",
        "@x402/core": "^2.19.0",
        "@x402/hono": "^2.19.0",
        hono: "^4.12.0",
      },
      devDependencies: {
        "@types/node": "^22.10.0",
        tsx: "^4.19.0",
        typescript: "^5.7.0",
      },
    },
    null,
    2,
  );
}

function buildReadme(params: { institutionName: string; title: string }): string {
  return `# ${params.institutionName} — Pacific Data Commons Endpoint

This package is your self-hosted Pacific Data Commons provider endpoint for
**${params.title}**, generated from your approved onboarding review.

## Before you deploy

1. Open \`index.ts\` and replace \`DATASET_RECORDS\` with your real dataset.
   Pacific Data Commons never receives or stores your data (data sovereignty
   is a core principle — see CLAUDE.md P1); this template only carries the
   listing metadata you approved during onboarding.
2. Copy \`.env.example\` to \`.env\` and fill in the required values.
3. Review \`pdp-schema.json\` — this is the Pacific Data Protocol schema for
   your dataset, pre-filled from your approved review.

## Local development

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploying

### Railway
1. Create a new Railway project from this directory (or push it to a Git
   repo and connect it).
2. Set the environment variables from \`.env.example\` in Railway's dashboard.
3. Railway auto-detects the Node.js app; the start command is \`npm start\`
   (build first with \`npm run build\`).
4. Set \`PUBLIC_URL\` to your Railway-assigned domain once deployed.

### Render
1. Create a new Web Service from this directory/repo.
2. Build command: \`npm install && npm run build\`. Start command: \`npm start\`.
3. Set the environment variables from \`.env.example\`.

### Your own VPS
1. Install Node.js 20+.
2. \`npm install && npm run build\`
3. Run \`npm start\` behind a process manager (pm2, systemd) and a reverse
   proxy (nginx/Caddy) terminating TLS.

## After deploying

Update your Pacific Data Commons listing with your live endpoint URL so
buyers and agents can be routed to it. Contact SBP if you need help.
`;
}

function buildEnvExample(): string {
  return `# Pacific Data Commons — Self-hosted provider endpoint
# Copy to .env. Never commit the real .env (CLAUDE.md P4: no secrets in code).

# Your Algorand wallet address — receives USDC payments directly (P2: SBP
# never holds funds, payments route straight to this address).
PROVIDER_WALLET=

# Algorand node access (optional — only needed if you add your own
# on-chain reads beyond what the x402 facilitator already handles).
NODELY_API_KEY=

# Optional — only needed if you choose to log queries back to your own
# Supabase project. Not required for the endpoint to run.
SUPABASE_URL=
SUPABASE_ANON_KEY=

# x402 facilitator (GoPlausible — CLAUDE.md Section 6)
FACILITATOR_URL=https://facilitator.goplausible.xyz

ALGORAND_NETWORK=mainnet
PORT=8080
# Set this to your deployed URL once you have one (Railway/Render/VPS).
PUBLIC_URL=http://localhost:8080
`;
}

function buildPdpSchema(params: {
  title: string;
  description: string;
  category: string;
  subCategory: string | null;
  geography: string | null;
  pricingTiers: PricingTier[];
}): string {
  return JSON.stringify(
    {
      schema_version: "pdp-1.0",
      title: params.title,
      description: params.description,
      category: params.category,
      sub_category: params.subCategory,
      geography: params.geography,
      pricing_tiers: params.pricingTiers,
      competition_tag: "x402-global-challenge",
    },
    null,
    2,
  );
}

/**
 * Step 6 self-hosted path. Reads the provider's approved listing (from the
 * `endpoints` row Step 4 created/updated) and builds a downloadable ZIP —
 * never touches the provider's actual dataset (CLAUDE.md P1), only the
 * metadata they already approved.
 */
export async function generateEndpointPackage(providerId: string, sessionToken: string): Promise<GeneratePackageResult> {
  try {
    await validateOnboardingSession(providerId, sessionToken);
  } catch (err) {
    return { success: false, error: err instanceof InvalidOnboardingSessionError ? err.message : "Invalid session." };
  }

  const supabase = createServiceClient();

  const { data: provider, error: providerError } = await supabase
    .from("providers")
    .select("institution_name, country")
    .eq("id", providerId)
    .maybeSingle();

  if (providerError || !provider) {
    console.error("Package generation — provider lookup failed:", providerError);
    return { success: false, error: "Could not find your provider record." };
  }

  const { data: endpoint, error: endpointError } = await supabase
    .from("endpoints")
    .select("title, description, data_category, data_sub_category, geography_region, pricing_tiers")
    .eq("provider_id", providerId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (endpointError || !endpoint) {
    console.error("Package generation — endpoint lookup failed:", endpointError);
    return { success: false, error: "Could not find your approved listing. Please complete Step 4 (Review) first." };
  }

  const pricingTiers = (endpoint.pricing_tiers ?? []) as PricingTier[];
  const providerSlug = slugify(provider.institution_name as string);

  const zip = new JSZip();
  zip.file(
    "index.ts",
    buildIndexTs({
      title: endpoint.title as string,
      description: endpoint.description as string,
      institutionName: provider.institution_name as string,
      country: provider.country as string,
      category: endpoint.data_category as string,
      subCategory: (endpoint.data_sub_category as string | null) ?? null,
      pricingTiers,
    }),
  );
  zip.file("package.json", buildPackageJson(providerSlug));
  zip.file("README.md", buildReadme({ institutionName: provider.institution_name as string, title: endpoint.title as string }));
  zip.file(".env.example", buildEnvExample());
  zip.file(
    "pdp-schema.json",
    buildPdpSchema({
      title: endpoint.title as string,
      description: endpoint.description as string,
      category: endpoint.data_category as string,
      subCategory: (endpoint.data_sub_category as string | null) ?? null,
      geography: (endpoint.geography_region as string | null) ?? null,
      pricingTiers,
    }),
  );

  const base64Zip = await zip.generateAsync({ type: "base64" });

  return { success: true, filename: `pdc-endpoint-${providerSlug}.zip`, base64Zip };
}
