-- ============================================================================
-- Session 37B — Deployment payment flow
-- Authority: CLAUDE.md v2.2, Section 7 (Node Deployment Service commercial
-- model) and the Session 37B build prompt.
--
-- deployment_invoices records every deployment service engagement with a
-- full payment audit trail. One row per provider upload session that
-- selects a paid deployment tier (self_service creates a row too, with
-- payment_status = 'not_required', so a provider's full deployment history
-- is queryable from one table regardless of tier chosen).
--
-- Linked to formatting_runs when a pipeline run exists; nullable because
-- complex/self-hosted deployments may bypass the pipeline entirely (a
-- provider can self-host without ever using the AI formatting service).
--
-- invoice_amount_usdc is currently always 0 for the 'assisted' tier — the
-- Session 37B promotional period (CLAUDE.md Section 7's "Currently Free —
-- Limited Time" SBP-assisted deployment). The schema supports a real
-- amount and a real payment_method so reintroducing pricing later requires
-- no schema change, only an application-layer constant and UI copy update.
-- ============================================================================

CREATE TABLE deployment_invoices (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Provider reference (always required)
  provider_id             UUID NOT NULL REFERENCES providers(id),

  -- Pipeline run reference (nullable — complex/self-hosted may not have one)
  formatting_run_id       UUID REFERENCES formatting_runs(id),

  -- Invoice identity
  invoice_reference       TEXT NOT NULL UNIQUE,
  -- Format: PDC-[YYYY]-[4-digit zero-padded sequence], e.g. PDC-2026-0001.
  -- Generated by the application layer (apps/web/lib/invoices/generateReference.ts),
  -- not the database. The UNIQUE constraint is the safety net against a
  -- race between two concurrent generations, not the primary mechanism.

  -- Deployment tier selected
  deployment_tier         TEXT NOT NULL
                          CHECK (deployment_tier IN (
                            'self_service',
                            -- Provider implements themselves — no payment
                            'assisted',
                            -- SBP deploys — payment required (currently free)
                            'complex'
                            -- SBP scopes first — payment after scoping.
                            -- No row is actually inserted for this tier in
                            -- Session 37B (contact happens outside the
                            -- platform via mailto) — the value is reserved
                            -- in the schema for when that changes.
                          )),

  -- Payment details
  invoice_amount_usdc     DECIMAL,
  -- NULL for self_service and complex (complex is quoted separately).
  -- 0 for 'assisted' during the free promotional period — a real amount
  -- once pricing is reintroduced.

  payment_method          TEXT
                          CHECK (payment_method IN (
                            'usdc',
                            'bank_transfer',
                            'not_applicable'
                            -- self_service requires no payment; assisted
                            -- during the free period also has no payment
                            -- method to record
                          )),

  payment_status          TEXT NOT NULL DEFAULT 'pending'
                          CHECK (payment_status IN (
                            'not_required',
                            -- self_service tier, or assisted during the free period
                            'pending',
                            -- Provider has selected a paid tier, payment not yet submitted
                            'submitted',
                            -- Provider clicked "I have sent payment"
                            'confirmed',
                            -- SBP has confirmed receipt
                            'bank_transfer_pending',
                            -- Bank transfer declared, awaiting clearance
                            'cancelled'
                            -- Provider cancelled or session expired
                          )),

  -- Provider-submitted payment evidence
  payment_submitted_at    TIMESTAMP WITH TIME ZONE,
  payment_tx_id           TEXT,
  -- USDC Algorand transaction ID (provider pastes this)
  payment_bank_ref        TEXT,
  -- Bank transfer reference (provider pastes this)

  -- SBP confirmation
  payment_confirmed_at    TIMESTAMP WITH TIME ZONE,
  -- Set via POST /api/invoices/confirm (apps/web), an internal-API-key-gated
  -- route SBP calls manually — see that route's doc comment for why this
  -- approach was chosen over a Postgres trigger + Supabase Edge Function.

  -- Email tracking
  acknowledgement_sent_at TIMESTAMP WITH TIME ZONE,
  -- When the "we received your request" email was sent to the provider
  sbp_notification_sent_at TIMESTAMP WITH TIME ZONE,
  -- When the SBP internal notification email was sent
  receipt_sent_at         TIMESTAMP WITH TIME ZONE,
  -- When the payment-confirmed receipt was sent to the provider

  -- SBP internal notes
  notes                   TEXT,

  -- Timestamps
  created_at              TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at              TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_deployment_invoices_provider
  ON deployment_invoices(provider_id);
CREATE INDEX idx_deployment_invoices_status
  ON deployment_invoices(payment_status)
  WHERE payment_status IN ('pending', 'submitted', 'bank_transfer_pending');
CREATE INDEX idx_deployment_invoices_reference
  ON deployment_invoices(invoice_reference);

-- updated_at trigger — reuses the shared update_updated_at() function
-- defined in session1_migration.sql (same pattern as providers, endpoints,
-- ogip_ministries, endpoint_deployments).
CREATE TRIGGER set_deployment_invoices_updated_at
  BEFORE UPDATE ON deployment_invoices
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- RLS
ALTER TABLE deployment_invoices ENABLE ROW LEVEL SECURITY;

-- Providers read their own invoices only
CREATE POLICY deployment_invoices_provider_read
  ON deployment_invoices FOR SELECT TO authenticated
  USING (
    provider_id IN (
      SELECT id FROM providers WHERE contact_email = auth.email()
    )
  );

-- Service role reads and writes all (for SBP confirmation updates) —
-- no policy needed beyond the service-role bypass Supabase applies by
-- default. No authenticated INSERT policy — invoices are created
-- server-side only (service role, from apps/web server actions). No
-- authenticated UPDATE policy — providers cannot modify payment_confirmed_at
-- or receipt_sent_at (SBP-only fields), same P11-style "no anon/authenticated
-- write path is added here on purpose" posture as session6_1_agent_schema.sql's
-- attribution records.

-- ── VERIFICATION QUERIES ────────────────────────────────────────
-- Run after applying this migration to confirm correctness.

-- Confirm table exists
-- SELECT tablename FROM pg_tables WHERE tablename = 'deployment_invoices';

-- Confirm RLS enabled
-- SELECT rowsecurity FROM pg_tables WHERE tablename = 'deployment_invoices';
-- Expected: true

-- Confirm unique constraint on invoice_reference
-- SELECT constraint_name FROM information_schema.table_constraints
-- WHERE table_name = 'deployment_invoices' AND constraint_type = 'UNIQUE';
